cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
  paths:
    - roman_blog/node_modules/
variables:
  IMAGE_NAME: romanarmin/next_blog
  IMAGE_TAG: v1 
before_script:
    - cd roman_blog
    - npm install
stages:
  - test
  - build
run_jest_tests:
  stage: test
  image: node:lts-alpine
  script:
    - npm run test
build_image:
  stage: build
  image: docker:27.0.0-rc.1-alpine3.20
  services:
    - docker:27.0.0-rc.1-dind-alpine3.20
  variables:
    DOCKER_TLS_CERT_DIR: "/certs"
  before_script:
  - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG -f roman_blog/Dockerfile roman_blog
    - docker push $IMAGE_NAME:$IMAGE_TAG 