cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
  paths:
    - roman_blog/node_modules/
before_script:
    - cd roman_blog
    - npm install
run_jest_tests:
    image: node:lts-alpine
    script:
        - npm run test
run_cypress_tests:
  image: cypress/browsers:node-20.14.0-chrome-125.0.6422.141-1-ff-126.0.1-edge-125.0.2535.85-1
  script:
    - npm ci
    - npm run build
    - npm start &
    - npx wait-on http://localhost:3000
    - npm run cypress:run