describe("homepage has all its elements", ()=>{
    beforeEach(()=>{
        cy.visit('http://localhost:3000/')
    })
    it("all content is displayed", ()=>{
        cy.get('.fullNavbar')
        .should('be.visible')
        cy.get('img[src="/images/programming.jpg"]')
        .should('be.visible')
        cy.get(".page_greeting__9ymoo")
        .should('be.visible')
        cy.get("body > div > div.footer_container__cL_uA")
        .should('be.visible')
    })
    it("navbar opens the correct pages",()=>{
        cy.get('.fullNavbar')
        .should('be.visible')
        cy.get('body > div > div.fullNavbar > div > div.navbar_mainNav__GbAmB > nav > ul > li:nth-child(1)')
        .click()
        cy.wait(3000)
        cy.url({timeout:5000}).should('contain', 'uebermich')
        cy.get('body > div > div.fullNavbar > div > div.navbar_mainNav__GbAmB > nav > ul > li:nth-child(2)')
        .click()
        cy.url({timeout:5000}).should('contain', 'blog')
        cy.get('body > div > div.fullNavbar > div > div.navbar_mainNav__GbAmB > nav > ul > li:nth-child(3)')
        .click()
        cy.url({timeout:5000}).should('contain', 'forum')
        cy.wait(10000)
        cy.get('body > div > div.fullNavbar > div > div.navbar_mainNav__GbAmB > nav > ul > li:nth-child(4)')
        .click()
        cy.url({timeout:20000}).should('contain', 'bibliothek')
        cy.get('body > div > div.fullNavbar > div > div.navbar_mainNav__GbAmB > nav > ul > li:nth-child(5)')
        .click()
        cy.url({timeout:10000}).should('contain', 'authUser/register')
    })
})