describe("All login functions work as expected", ()=>{
    it("login works, with expected redirection for user", ()=>{
        cy.visit('http://localhost:3000/authUser/login')
        cy.get("#username")
        .wait(3000) // wait for 1 second
        .focus()
        .type("TesterMartin")
        .should('have.value', 'TesterMartin')
        cy.get('#email')
        .type('testerMartin@test.de')
        .should('have.value', 'testerMartin@test.de')
        cy.get('#password')
        .type("123456")
        cy.get('#loginBtn')
        .click()
        cy.url({timeout:10000})
        .should('eq', 'http://localhost:3000/')
    })
    it("login works, with the expected redirection for the admin", ()=>{
        cy.visit('http://localhost:3000/authUser/login')
        cy.get('#username')
        .type("RomanArmin")
        .should('have.value', 'RomanArmin')
        cy.get('#email')
        .type('roman.rostock@googlemail.com')
        .should('have.value', 'roman.rostock@googlemail.com')
        cy.get('#password')
        .type('874123')
        cy.get('#loginBtn')
        .click()
        cy.url({timeout:30000})
        .should('eq', 'http://localhost:3000/dashboard')
    })
    it("PasswordForgotten should work", ()=>{
        cy.visit('http://localhost:3000/authUser/login')
        cy.get('#username')
        .wait(1000) // wait for 1 second
        .focus()
        .type("TesterMartin")
        .should('have.value', 'TesterMartin')
        cy.get('#email')
        .type('testerMartin@test.de')
        .should('have.value', 'testerMartin@test.de')
        cy.get('#forgottenBtn')
        .click()
    })
})