before_script:
    - npm install
run_jest_tests:
    image: node:lts-alpine
    script:
        - npm run test
run_cypress_tests:
  image: cypress/browsers:node-12.18.0-chrome83-ff77
  script:
    - npm run start:ci &
    - npx cypress run